import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavBar } from "../components/nav/NavBar";
import { AuthProvider } from "../context/AuthContext";
import { PageBackground } from "../components/layout/PageBackground";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`isolate relative text-gray-100 overflow-x-hidden ${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <NavBar />
          <PageBackground
            image="https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=1600&q=80"
            startBelowNav
            overlayOpacity={50}
            overlayTint="light"
          />
          <div className="relative z-10 pt-6 pb-12 min-h-screen">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
